---
- name: This playbooks to install apache httpd and start httpd on server
  hosts: centos
  become: yes
  tags: install

  tasks:
    - name: install apache on server
      yum:
        name: httpd
        state: latest

    - name: make sure apache is started and run
      systemd:
        name: httpd
        state: started
        enabled: yes

- name: This playbooks to uninstall apache httpd
  hosts: centos
  become: yes
  tags: remove

  tasks:
    - name: uninstall apache on server
      yum:
        name: httpd
        state: absent
