---
## You are making mistake by not add extra vars
- name: This playbooks to uninstall apache httpd
  hosts: all
  become: yes

  tasks:
    - name: uninstall apache on server
      yum:
        name: httpd
        state: absent
