---
- name: This playbook is to install apache httpd and start.
  hosts: all
  become: yes

  tasks:
    - name: Install Apache on all server
      yum:
        name: httpd
        state: latest

    - name: make sure Apache is started and enabled
      systemd:
        name: httpd
        state: started
        enabled: yes

<<<<<<< HEAD
- name: This playbook is to uninstall apache httpd and remove.
=======

- name: This playbook is to uninstall apache httpd and start.
>>>>>>> 017dae742011d707d463dab7eeeda94b732d94bb
  hosts: all
  become: yes

  tasks:
    - name: Uninstall Apache on all server
      yum:
        name: httpd
        state: absent
