---
- name: This playbooks to install apache httpd and start httpd on server
  hosts: all
  become: yes

  tasks:
    - name: install apache on server
      yum:
        name: httpd
        state: latest

    - name: make sure apache is started and run
      systemd:
        name: httpd
        state: started
        enabled: yes
