---
- name: sample user creation 
  hosts: rocky
  become: true
  tasks:
    - name: user example present
      ansible.builtin.user:
        name: RnD
        password: "{{ 'password' | password_hash('sha512', 'mysecretsalt') }}"
        groups:
          - wheel
        state: "present"
        shell: "/bin/bash"
        system: false
        create_home: true
        home: "/home/RnD"
        comment: "Ansible example"
        generate_ssh_key: true
