---
- name: this playbook will be use to create a user on server
  hosts: all

  tasks:
  - name: Add the user 'Hassan' with specific uid and a primary group of 'finance'
    ansible.builtin.user:
      name: Hassan
      comment: Hassan Damala
      uid: 1091
      group: finance
